server:
  port: 8080

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/myvue?useUnicode=true&characterEncoding=UTF8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

#mybatis配置
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.test.domain

#日志配置
logging:
  config: classpath:logback.xml
  level:
    com.example.test: debug
